package hello;

import java.util.ArrayList;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.google.common.collect.Lists;
import java.util.Optional;

@Controller    // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
@RequestMapping(path = "/libraryall") // This means URL's start with /demo (after Application path)
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@RequestParam String name, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();

    }

    // work-in-progress ..... vad ska jag göra för att returnera en specifik användare ex name=kevin
    // https://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html
    @GetMapping(path = "/some")
    public @ResponseBody
    Optional<User> getSpecificUser() {
        // This returns a JSON or XML with the users
        Iterable<User> all = userRepository.findAll();

        String name = "maliheh";
        List<User> myList = Lists.newArrayList(all);
        
        Optional<User> findFirst = myList.stream().filter(c->c.getName().equals(name)).findFirst();
        System.out.println("*****");
        System.out.println("***** "+findFirst);
        System.out.println("*****");
        
        
           
        return findFirst;
    }
}
